### ISSUE TITLE
Installation of this mod failed.

### ISSUE THREAD

**Issue by madjack98** [JediNick/Valyrian_Steel#1]
Hey, I've been trying to get this version of the mod to work, I've installed all other mods right but this one claims to have an invalid descriptor file path. I tried checking the .mod file myself to see what's the issue and it seems like the path is only designated as "PATH" instead of an ID the rest of your .mod files uses

Could you look into it if it isn't too big of a bother? I'd download the steam version if I could just to not be annoying but I unfortunately dont own the game on Steam.

Thank you in advance!

**Comment by JediNick** [comment]
ID is only really relevant to Steam anyways, you need to replace "PATH" with you local install path.
